import React, { useState, useMemo } from 'react';
import { Download, Printer, FileText, Check, X, Star, Tag, Filter, Calendar, Briefcase, Layers, Users } from 'lucide-react';
import toast from 'react-hot-toast';

function escapeCsvCell(cell) {
  if (cell == null) return '""';
  const str = String(cell);
  if (str.includes('"') || str.includes(',') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return `"${str}"`;
}

export default function SearchReportModal({
  isOpen,
  onClose,
  candidates = [],
  selectedKeys = new Set(),
  candidateKey = (c) => `${c.is_employee ? 'employee' : 'candidate'}-${c.id}`,
  filters = {},
  jobRoles = [],
  currentUser = null,
}) {
  const [exportScope, setExportScope] = useState(() => (selectedKeys.size > 0 ? 'selected' : 'all'));
  const [managerNotes, setManagerNotes] = useState('');
  const [includeSkills, setIncludeSkills] = useState(true);

  const selectedRole = useMemo(() => {
    if (!filters.role_id) return null;
    return jobRoles.find(r => r.id === parseInt(filters.role_id)) || null;
  }, [filters.role_id, jobRoles]);

  // Determine candidate list to export based on scope
  const targetCandidates = useMemo(() => {
    if (exportScope === 'selected' && selectedKeys.size > 0) {
      return candidates.filter(c => selectedKeys.has(candidateKey(c)));
    }
    return candidates;
  }, [exportScope, candidates, selectedKeys, candidateKey]);

  // Summary statistics
  const stats = useMemo(() => {
    const total = targetCandidates.length;
    const scored = targetCandidates.filter(c => c.ats_score != null);
    const avgScore = scored.length > 0 
      ? Math.round(scored.reduce((acc, c) => acc + c.ats_score, 0) / scored.length) 
      : null;
    const highFit = targetCandidates.filter(c => (c.ats_score || 0) >= 70).length;
    const moderateFit = targetCandidates.filter(c => (c.ats_score || 0) >= 40 && (c.ats_score || 0) < 70).length;
    
    return { total, scoredCount: scored.length, avgScore, highFit, moderateFit };
  }, [targetCandidates]);

  // Formatted period text
  const periodText = useMemo(() => {
    const years = filters.upload_years || [];
    const months = filters.upload_months || [];
    if (years.length === 0 && months.length === 0) return 'All Time (All Years & Months)';
    
    const monthNames = months.map(m => {
      const idx = parseInt(m, 10) - 1;
      return new Date(2000, idx).toLocaleString('default', { month: 'short' });
    });

    if (years.length > 0 && months.length > 0) {
      return `${monthNames.join(', ')} of ${years.join(', ')}`;
    }
    if (years.length > 0) return `Year(s): ${years.join(', ')}`;
    return `Month(s): ${monthNames.join(', ')}`;
  }, [filters.upload_years, filters.upload_months]);

  const roleTagsText = useMemo(() => {
    if (!filters.role_tags || filters.role_tags.length === 0) return 'All Role Tags';
    return filters.role_tags.join(', ');
  }, [filters.role_tags]);

  if (!isOpen) return null;

  /* ── CSV Generator ── */
  const handleDownloadCsv = () => {
    if (targetCandidates.length === 0) {
      toast.error('No candidates available to export');
      return;
    }

    try {
      const now = new Date();
      const dateStr = now.toLocaleDateString();
      const timeStr = now.toLocaleTimeString();

      const metadataRows = [
        ['PHYGITRON 360 - TALENT VAULT CANDIDATE SCREENING REPORT'],
        ['Report Generated At', `${dateStr} ${timeStr}`],
        ['Generated By', currentUser?.full_name || currentUser?.name || currentUser?.email || 'Hiring Manager'],
        ['Target Job Role', selectedRole ? selectedRole.title : 'None Selected (General Search)'],
        ['Talent Pool', filters.pool || 'All'],
        ['Upload Period Filter', periodText],
        ['Role Tags Filter', roleTagsText],
        ['Search Query', filters.search || 'None'],
        ['Location Filter', filters.location || 'Any'],
        ['Experience Filter', filters.exp_range || 'Any'],
        ['Total Candidates in Report', targetCandidates.length],
        ['Average Fit Score', stats.avgScore != null ? `${stats.avgScore}%` : 'N/A'],
        ['Manager Remarks & Notes', managerNotes ? managerNotes.replace(/\r?\n/g, ' ') : 'None'],
        [], // empty separator
      ];

      const headerRow = [
        'Rank',
        'Candidate Name',
        'Email Address',
        'Location',
        'Experience (Years)',
        'Candidate Type',
        'Status',
        'Role Tag',
        'Target Role Fit (%)',
        'Baseline ATS Score',
        'Matched Skills',
        'Missing Skills',
        'All Skills & Proficiency',
        'Uploaded Date',
        'Manager Screening Remarks'
      ];

      const dataRows = targetCandidates.map((c, idx) => {
        const fitReason = c.fit_reason || {};
        const matched = (fitReason.matched_skills || []).map(s => `${s.skill} (${s.candidate_level || s.level || 'aligned'})`).join('; ');
        const missing = (fitReason.missing_skills || []).map(s => `${s.skill} (req: ${s.required_level || s.level || 'any'})`).join('; ');
        const allSkills = (c.skills || []).map(s => `${s.name} [${s.level || 'proficient'}]`).join('; ');
        const uploadDate = c.created_at ? new Date(c.created_at).toLocaleDateString() : 'N/A';

        return [
          idx + 1,
          c.name || 'Unknown',
          c.email || '',
          c.location || 'Not Specified',
          c.exp_years ?? 0,
          c.type || 'Candidate',
          c.status || 'Active',
          c.role_folder || 'Unassigned',
          c.ats_score != null ? `${Math.round(c.ats_score)}%` : 'N/A',
          c.resume_ats_score != null ? `${Math.round(c.resume_ats_score)}/100` : 'N/A',
          matched || 'N/A',
          missing || 'None',
          allSkills || 'None detected',
          uploadDate,
          managerNotes ? managerNotes.replace(/\r?\n/g, ' ') : ''
        ];
      });

      const allRows = [
        ...metadataRows.map(r => r.map(escapeCsvCell).join(',')),
        headerRow.map(escapeCsvCell).join(','),
        ...dataRows.map(r => r.map(escapeCsvCell).join(','))
      ];

      // Add UTF-8 BOM for Microsoft Excel compatibility
      const csvContent = '\uFEFF' + allRows.join('\r\n');
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      const cleanRole = selectedRole ? selectedRole.title.toLowerCase().replace(/[^a-z0-9]/g, '_') : 'screening';
      link.href = url;
      link.download = `Talent_Vault_Report_${cleanRole}_${now.toISOString().split('T')[0]}.csv`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast.success('CSV Report downloaded successfully!');
    } catch (err) {
      console.error('Failed to export CSV:', err);
      toast.error('Failed to generate CSV report');
    }
  };

  /* ── HTML / Printable Report Builder ── */
  const buildReportHtml = () => {
    const now = new Date();
    const dateFormatted = now.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });
    const timeFormatted = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    const userName = currentUser?.full_name || currentUser?.name || currentUser?.email || 'Hiring Manager';

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Talent Vault Screening Report - Phygitron 360</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      color: #0f172a;
      background: #ffffff;
      padding: 24px;
      line-height: 1.45;
      font-size: 13px;
    }
    @page {
      size: A4 portrait;
      margin: 12mm 10mm;
    }
    @media print {
      body { padding: 0; }
      .no-print { display: none !important; }
      .page-break { page-break-before: always; }
      tr { page-break-inside: avoid; }
    }
    .report-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 2px solid #7c3aed;
      padding-bottom: 14px;
      margin-bottom: 16px;
    }
    .brand-title {
      font-size: 20px;
      font-weight: 800;
      color: #7c3aed;
      letter-spacing: -0.5px;
    }
    .brand-sub {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: #64748b;
      font-weight: 600;
      margin-top: 2px;
    }
    .meta-box {
      text-align: right;
      font-size: 11px;
      color: #475569;
    }
    .meta-box strong { color: #0f172a; }
    
    .grid-summary {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 12px;
      margin-bottom: 16px;
    }
    .stat-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 10px 14px;
      text-align: center;
    }
    .stat-num {
      font-size: 20px;
      font-weight: 800;
      color: #7c3aed;
    }
    .stat-label {
      font-size: 11px;
      font-weight: 600;
      color: #64748b;
      text-transform: uppercase;
    }

    .section-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 12px 16px;
      margin-bottom: 16px;
    }
    .section-title {
      font-size: 12px;
      font-weight: 700;
      color: #334155;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 6px;
    }
    .filter-pills {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
      font-size: 12px;
    }
    .pill {
      background: #ffffff;
      border: 1px solid #cbd5e1;
      padding: 3px 10px;
      border-radius: 6px;
      font-weight: 500;
      color: #1e293b;
    }
    .pill-highlight {
      background: #ede9fe;
      border-color: #c4b5fd;
      color: #5b21b6;
      font-weight: 700;
    }

    .manager-notes-box {
      background: #fffbeb;
      border-left: 4px solid #f59e0b;
      padding: 10px 14px;
      border-radius: 0 8px 8px 0;
      margin-bottom: 16px;
      font-size: 12px;
      color: #78350f;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 8px;
      font-size: 11.5px;
    }
    th {
      background: #f1f5f9;
      color: #334155;
      font-weight: 700;
      text-align: left;
      padding: 8px 10px;
      border-bottom: 2px solid #cbd5e1;
      font-size: 11px;
      text-transform: uppercase;
    }
    td {
      padding: 8px 10px;
      border-bottom: 1px solid #e2e8f0;
      vertical-align: top;
    }
    tr:nth-child(even) td {
      background: #fafafa;
    }
    .score-badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 12px;
      font-weight: 800;
      font-size: 11px;
      text-align: center;
    }
    .score-green { background: #dcfce7; color: #166534; }
    .score-amber { background: #fef3c7; color: #92400e; }
    .score-red { background: #fee2e2; color: #991b1b; }
    .tag-badge {
      background: #f1f5f9;
      color: #475569;
      border: 1px solid #cbd5e1;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 10px;
      font-weight: 600;
      display: inline-block;
    }
    .skill-chip {
      display: inline-block;
      background: #ede9fe;
      color: #6d28d9;
      padding: 1px 5px;
      border-radius: 3px;
      font-size: 10px;
      margin: 1px;
      font-weight: 500;
    }
    .notes-space {
      width: 140px;
      border: 1px dashed #cbd5e1;
      height: 32px;
      border-radius: 4px;
      background: #ffffff;
      padding: 2px 4px;
      font-size: 10px;
      color: #64748b;
    }
    .footer {
      margin-top: 24px;
      padding-top: 10px;
      border-top: 1px solid #e2e8f0;
      display: flex;
      justify-content: space-between;
      font-size: 10px;
      color: #94a3b8;
    }
  </style>
</head>
<body>
  <div class="report-header">
    <div>
      <div class="brand-title">PHYGITRON 360</div>
      <div class="brand-sub">Talent Vault Candidate Screening Report</div>
    </div>
    <div class="meta-box">
      <div><strong>Date:</strong> ${dateFormatted} ${timeFormatted}</div>
      <div><strong>Reviewer:</strong> ${userName}</div>
      <div><strong>Target Role:</strong> ${selectedRole ? selectedRole.title : 'General Search (No Role)'}</div>
    </div>
  </div>

  <div class="grid-summary">
    <div class="stat-card">
      <div class="stat-num">${stats.total}</div>
      <div class="stat-label">Candidates</div>
    </div>
    <div class="stat-card">
      <div class="stat-num">${stats.avgScore != null ? stats.avgScore + '%' : '—'}</div>
      <div class="stat-label">Avg Role Fit</div>
    </div>
    <div class="stat-card">
      <div class="stat-num">${stats.highFit}</div>
      <div class="stat-label">High Fit (&ge;70%)</div>
    </div>
    <div class="stat-card">
      <div class="stat-num">${stats.moderateFit}</div>
      <div class="stat-label">Moderate Fit (40-69%)</div>
    </div>
  </div>

  <div class="section-card">
    <div class="section-title">Applied Search Criteria</div>
    <div class="filter-pills">
      <div class="pill ${selectedRole ? 'pill-highlight' : ''}">🎯 Role: ${selectedRole ? selectedRole.title : 'Any Role'}</div>
      <div class="pill">📁 Period: ${periodText}</div>
      <div class="pill">🏷️ Tags: ${roleTagsText}</div>
      <div class="pill">👥 Pool: ${filters.pool || 'All'}</div>
      ${filters.search ? `<div class="pill">🔍 Query: "${filters.search}"</div>` : ''}
      ${filters.location ? `<div class="pill">📍 Loc: ${filters.location}</div>` : ''}
      ${filters.exp_range ? `<div class="pill">💼 Exp: ${filters.exp_range}</div>` : ''}
    </div>
  </div>

  ${managerNotes ? `
  <div class="manager-notes-box">
    <strong>Manager Screening Notes:</strong><br>
    ${managerNotes.replace(/\n/g, '<br>')}
  </div>
  ` : ''}

  <table>
    <thead>
      <tr>
        <th style="width: 24px;">#</th>
        <th style="width: 170px;">Candidate Details</th>
        <th style="width: 65px;">Exp / Loc</th>
        <th style="width: 90px;">Role Tag</th>
        <th style="width: 75px; text-align: center;">Fit Score</th>
        <th>Key Skills</th>
        <th style="width: 150px;">Manager Remarks / Actions</th>
      </tr>
    </thead>
    <tbody>
      ${targetCandidates.map((c, i) => {
        const score = c.ats_score != null ? Math.round(c.ats_score) : null;
        const scoreClass = score == null ? '' : score >= 70 ? 'score-green' : score >= 40 ? 'score-amber' : 'score-red';
        const skillsList = (c.skills || []).slice(0, 6);
        const moreSkills = (c.skills || []).length - skillsList.length;

        return `
        <tr>
          <td style="font-weight: 700; color: #7c3aed;">${i + 1}</td>
          <td>
            <strong style="color: #0f172a; font-size: 12px;">${c.name || 'Unknown'}</strong>
            <div style="color: #64748b; font-size: 11px;">${c.email || ''}</div>
            <div style="font-size: 10px; color: #94a3b8;">${c.type || 'Candidate'} · ${c.status || 'Active'}</div>
          </td>
          <td>
            <div>${c.exp_years > 0 ? c.exp_years + ' yrs' : 'Fresher'}</div>
            <div style="font-size: 10px; color: #64748b;">${c.location || '—'}</div>
          </td>
          <td>
            ${c.role_folder ? `<span class="tag-badge">${c.role_folder}</span>` : '<span style="color: #94a3b8; font-size: 10px;">Unassigned</span>'}
          </td>
          <td style="text-align: center;">
            ${score != null ? `<span class="score-badge ${scoreClass}">${score}%</span>` : '<span style="color: #94a3b8;">—</span>'}
            ${c.resume_ats_score ? `<div style="font-size: 9px; color: #94a3b8; margin-top: 2px;">ATS: ${Math.round(c.resume_ats_score)}</div>` : ''}
          </td>
          <td>
            <div>
              ${skillsList.map(s => `<span class="skill-chip">${s.name}</span>`).join(' ')}
              ${moreSkills > 0 ? `<span style="font-size: 9px; color: #94a3b8;">+${moreSkills} more</span>` : ''}
            </div>
          </td>
          <td>
            <div class="notes-space">
              <span style="font-size: 9px; color: #94a3b8;">[ ] Interview &nbsp; [ ] Hold &nbsp; [ ] Reject</span>
            </div>
          </td>
        </tr>
        `;
      }).join('')}
    </tbody>
  </table>

  <div class="footer">
    <div>Phygitron 360 Talent Vault · Confidential Screening Document</div>
    <div>Report generated on ${dateFormatted}</div>
  </div>
</body>
</html>`;
  };

  /* ── Print / Save as PDF ── */
  const handlePrintPdf = () => {
    if (targetCandidates.length === 0) {
      toast.error('No candidates available to export');
      return;
    }

    try {
      const htmlContent = buildReportHtml();
      
      // Use hidden iframe to avoid popup blocker issues
      const iframe = document.createElement('iframe');
      iframe.style.position = 'fixed';
      iframe.style.right = '0';
      iframe.style.bottom = '0';
      iframe.style.width = '0';
      iframe.style.height = '0';
      iframe.style.border = '0';
      document.body.appendChild(iframe);

      iframe.contentWindow.document.open();
      iframe.contentWindow.document.write(htmlContent);
      iframe.contentWindow.document.close();

      setTimeout(() => {
        iframe.contentWindow.focus();
        iframe.contentWindow.print();
        setTimeout(() => {
          if (document.body.contains(iframe)) {
            document.body.removeChild(iframe);
          }
        }, 2000);
      }, 350);

      toast.success('Opening print / PDF dialog...');
    } catch (err) {
      console.error('Print failed:', err);
      toast.error('Failed to trigger print dialog');
    }
  };

  /* ── Standalone HTML Download ── */
  const handleDownloadHtml = () => {
    if (targetCandidates.length === 0) {
      toast.error('No candidates available to export');
      return;
    }

    try {
      const htmlContent = buildReportHtml();
      const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      const cleanRole = selectedRole ? selectedRole.title.toLowerCase().replace(/[^a-z0-9]/g, '_') : 'screening';
      link.href = url;
      link.download = `Talent_Vault_Report_${cleanRole}_${new Date().toISOString().split('T')[0]}.html`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast.success('HTML Report downloaded successfully!');
    } catch (err) {
      console.error('HTML export failed:', err);
      toast.error('Failed to download HTML report');
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose} style={{ zIndex: 600 }}>
      <div 
        className="modal animate-scale-in" 
        onClick={e => e.stopPropagation()} 
        style={{ maxWidth: 680, width: '95%', maxHeight: '90vh', display: 'flex', flexDirection: 'column' }}
      >
        {/* Header */}
        <div className="modal-header" style={{ padding: '18px 24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div style={{ width: 36, height: 36, borderRadius: 10, background: 'rgba(124, 58, 237, 0.12)', border: '1px solid rgba(124, 58, 237, 0.25)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--primary)' }}>
              <FileText size={20} />
            </div>
            <div>
              <h3 style={{ fontSize: '1.15rem', fontWeight: 800, margin: 0 }}>Talent Vault Search Report</h3>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', margin: 0 }}>Export & note down candidate screening findings for your team</p>
            </div>
          </div>
          <button className="btn btn-ghost btn-sm" onClick={onClose} style={{ padding: 6 }}><X size={16} /></button>
        </div>

        {/* Body */}
        <div className="modal-body" style={{ padding: '20px 24px', overflowY: 'auto', flex: 1, display: 'flex', flexDirection: 'column', gap: 18 }}>
          
          {/* Export Scope Selector (if candidates are selected) */}
          {selectedKeys.size > 0 && (
            <div style={{ background: 'var(--bg-card-alt, rgba(124, 58, 237, 0.08))', border: '1px solid rgba(124, 58, 237, 0.2)', borderRadius: 12, padding: '12px 16px' }}>
              <label style={{ fontSize: '0.82rem', fontWeight: 700, color: 'var(--primary)', marginBottom: 8, display: 'block' }}>Report Scope</label>
              <div style={{ display: 'flex', gap: 16 }}>
                <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '0.88rem', cursor: 'pointer' }}>
                  <input 
                    type="radio" 
                    name="scope" 
                    value="all" 
                    checked={exportScope === 'all'} 
                    onChange={() => setExportScope('all')} 
                    style={{ accentColor: 'var(--primary)' }}
                  />
                  <span>All Search Results ({candidates.length})</span>
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '0.88rem', cursor: 'pointer' }}>
                  <input 
                    type="radio" 
                    name="scope" 
                    value="selected" 
                    checked={exportScope === 'selected'} 
                    onChange={() => setExportScope('selected')} 
                    style={{ accentColor: 'var(--primary)' }}
                  />
                  <span style={{ fontWeight: 600, color: 'var(--primary)' }}>Only Selected Resumes ({selectedKeys.size})</span>
                </label>
              </div>
            </div>
          )}

          {/* Search Criteria Snapshot */}
          <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 12, padding: '14px 16px' }}>
            <div style={{ fontSize: '0.78rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 8, letterSpacing: '0.5px' }}>
              Search Context Snapshot
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))', gap: 10, fontSize: '0.82rem' }}>
              <div>
                <span style={{ color: 'var(--text-muted)' }}>Target Role: </span>
                <strong>{selectedRole ? selectedRole.title : 'Any Role'}</strong>
              </div>
              <div>
                <span style={{ color: 'var(--text-muted)' }}>Period: </span>
                <strong>{periodText}</strong>
              </div>
              <div>
                <span style={{ color: 'var(--text-muted)' }}>Role Tag: </span>
                <strong>{roleTagsText}</strong>
              </div>
              <div>
                <span style={{ color: 'var(--text-muted)' }}>Pool: </span>
                <strong style={{ textTransform: 'capitalize' }}>{filters.pool || 'All'}</strong>
              </div>
              <div>
                <span style={{ color: 'var(--text-muted)' }}>Found Candidates: </span>
                <strong style={{ color: 'var(--primary)' }}>{targetCandidates.length}</strong>
              </div>
              {stats.avgScore != null && (
                <div>
                  <span style={{ color: 'var(--text-muted)' }}>Avg Role Fit: </span>
                  <strong style={{ color: 'var(--success)' }}>{stats.avgScore}%</strong>
                </div>
              )}
            </div>
          </div>

          {/* Manager's Screening Notes Textarea */}
          <div className="form-group" style={{ margin: 0 }}>
            <label className="form-label" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span>Manager Screening Notes & Directives (Optional)</span>
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: 400 }}>Will be included in the report</span>
            </label>
            <textarea
              className="form-control"
              rows={3}
              placeholder="e.g. Shortlisted for Senior AI Engineer hiring drive. Candidates 1 & 2 prioritize for Round 1 technical interview. Focus on PyTorch experience."
              value={managerNotes}
              onChange={e => setManagerNotes(e.target.value)}
              style={{ fontSize: '0.88rem', resize: 'vertical' }}
            />
          </div>

          {/* Export Options Cards */}
          <div>
            <label className="form-label" style={{ marginBottom: 10 }}>Select Export Format</label>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 12 }}>
              
              {/* CSV Card */}
              <div 
                onClick={handleDownloadCsv}
                style={{ 
                  border: '1px solid var(--border)', 
                  borderRadius: 12, 
                  padding: '16px', 
                  cursor: 'pointer', 
                  background: 'var(--bg-card)', 
                  transition: 'var(--transition)',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 8
                }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = 'var(--primary)'; e.currentTarget.style.transform = 'translateY(-2px)'; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.transform = 'none'; }}
              >
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <div style={{ width: 34, height: 34, borderRadius: 8, background: 'rgba(16, 185, 129, 0.12)', color: 'var(--success)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <Download size={18} />
                  </div>
                  <span className="badge badge-success" style={{ fontSize: '0.7rem' }}>Excel / CSV</span>
                </div>
                <div>
                  <div style={{ fontWeight: 700, fontSize: '0.92rem', color: 'var(--text-primary)' }}>CSV Spreadsheet</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 2 }}>
                    Spreadsheet with scores, skills, contact info, and notes columns.
                  </div>
                </div>
                <button className="btn btn-secondary btn-sm" style={{ width: '100%', marginTop: 6, fontSize: '0.8rem', justifyContent: 'center' }}>
                  <Download size={13} /> Download .CSV
                </button>
              </div>

              {/* PDF Print Card */}
              <div 
                onClick={handlePrintPdf}
                style={{ 
                  border: '1px solid var(--border)', 
                  borderRadius: 12, 
                  padding: '16px', 
                  cursor: 'pointer', 
                  background: 'var(--bg-card)', 
                  transition: 'var(--transition)',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 8
                }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = 'var(--primary)'; e.currentTarget.style.transform = 'translateY(-2px)'; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.transform = 'none'; }}
              >
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <div style={{ width: 34, height: 34, borderRadius: 8, background: 'rgba(124, 58, 237, 0.12)', color: 'var(--primary)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <Printer size={18} />
                  </div>
                  <span className="badge badge-primary" style={{ fontSize: '0.7rem' }}>Print / PDF</span>
                </div>
                <div>
                  <div style={{ fontWeight: 700, fontSize: '0.92rem', color: 'var(--text-primary)' }}>Executive PDF Report</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 2 }}>
                    Formatted report with KPIs, candidate scorecards, and printable notes.
                  </div>
                </div>
                <button className="btn btn-primary btn-sm" style={{ width: '100%', marginTop: 6, fontSize: '0.8rem', justifyContent: 'center' }}>
                  <Printer size={13} /> Print / Save PDF
                </button>
              </div>

              {/* Standalone HTML Card */}
              <div 
                onClick={handleDownloadHtml}
                style={{ 
                  border: '1px solid var(--border)', 
                  borderRadius: 12, 
                  padding: '16px', 
                  cursor: 'pointer', 
                  background: 'var(--bg-card)', 
                  transition: 'var(--transition)',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 8
                }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = 'var(--primary)'; e.currentTarget.style.transform = 'translateY(-2px)'; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.transform = 'none'; }}
              >
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <div style={{ width: 34, height: 34, borderRadius: 8, background: 'rgba(6, 182, 212, 0.12)', color: 'var(--accent-2)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <FileText size={18} />
                  </div>
                  <span className="badge badge-secondary" style={{ fontSize: '0.7rem' }}>Offline File</span>
                </div>
                <div>
                  <div style={{ fontWeight: 700, fontSize: '0.92rem', color: 'var(--text-primary)' }}>HTML Document</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 2 }}>
                    Standalone file for email sharing or offline viewing in browser.
                  </div>
                </div>
                <button className="btn btn-secondary btn-sm" style={{ width: '100%', marginTop: 6, fontSize: '0.8rem', justifyContent: 'center' }}>
                  <FileText size={13} /> Download .HTML
                </button>
              </div>

            </div>
          </div>

        </div>

        {/* Footer */}
        <div className="modal-footer" style={{ padding: '14px 24px' }}>
          <button className="btn btn-ghost" onClick={onClose} style={{ fontWeight: 600 }}>
            Close
          </button>
          <div style={{ display: 'flex', gap: 10 }}>
            <button className="btn btn-secondary" onClick={handleDownloadCsv}>
              <Download size={14} /> Download CSV
            </button>
            <button className="btn btn-primary" onClick={handlePrintPdf}>
              <Printer size={14} /> Print / Save PDF
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
